[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next" # This is typically the output directory for Next.js on Netlify

[[plugins]]
  package = "@netlify/plugin-nextjs"
